{{/*
SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
SPDX-FileCopyrightText: Copyright (c) 2026 KubeTEE AI LTD
SPDX-License-Identifier: Apache-2.0
*/}}
{{- $secretValues := get .Values "secret" | default dict }}
{{- $extraSecretData := get $secretValues "extraStringData" | default dict }}
{{- if and (not .Values.existingSecret) (or .Values.nvidiaApiKey (gt (len $extraSecretData) 0)) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nemoclaw.fullname" . }}-nvidia
  labels:
    {{- include "nemoclaw.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $k := .Values.existingSecretKey | default "nvidia-api-key" }}
  {{- if .Values.nvidiaApiKey }}
  {{ $k }}: {{ .Values.nvidiaApiKey | quote }}
  {{- end }}
  {{- range $extraKey, $extraValue := $extraSecretData }}
  {{ $extraKey }}: {{ $extraValue | quote }}
  {{- end }}
{{- end }}
